---
- hosts: all
  remote_user: limn1
  vars:
    # your extra bundles here
    #zsh_antigen_bundles_extras:
    # your variables here
    #zsh_autosuggestions_bind_key: "^U"
  roles:
    - role: 'roles/nathanmlim'
    #- viasite-ansible.zsh
