---
- hosts: all
  vars:
    # your extra bundles here
    zsh_antigen_bundles_extras:
      # Completion Plugins
      - zsh-users/zsh-completions
      - chrissicool/zsh-bash
      # - robbyrussell/oh-my-zsh folder:plugins/gitfast
      # - robbyrussell/oh-my-zsh folder:plugins/git-extras
      # - robbyrussell/oh-my-zsh folder:plugins/pip
      # - robbyrussell/oh-my-zsh folder:plugins/python
      # - robbyrussell/oh-my-zsh folder:plugins/brew
      # #robbyrussell/oh-my-zsh folder:plugins/osx
      # Color plugins
      - gretzky/auto-color-ls
      - ael-code/zsh-colored-man-pages
      # Git plugins
      - denolfe/zsh-travis
      - rutchkiwi/copyzshell
      # iTerm plugins
      - tysonwolker/iterm-tab-colors
      - iam4x/zsh-iterm-touchbar
      - zsh-users/zsh-autosuggestions
      - zsh-users/zsh-history-substring-search
      - popstas/zsh-command-time
      - paulmelnikow/zsh-startup-timer
      - trapd00r/zsh-syntax-highlighting-filetypes
      - zdharma/fast-syntax-highlighting
    # your variables here
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - viasite-ansible.zsh
