---

# - name: Install zsh, git, wget
#   package:
#     name: "{{ item }}"
#     state: present
#   with_items:
#     - zsh
#     - git
#     - wget
#   # brew don't work from root user on macOS
#   when: not (zsh_user == 'root' and ansible_os_family == 'Darwin')
#
- name: Clone antigen {{ zsh_antigen_version }}
  git:
    repo: https://github.com/zsh-users/antigen.git
    dest: "/home/{{ zsh_user }}/antigen"
    version: "{{ zsh_antigen_version }}"
    force: yes
  become: yes
  become_user: "{{ zsh_user }}"
  register: zsh_register_antigen_clone
#

- name: Check fzf installed
  command: which fzf
  changed_when: false
  failed_when: false
  register: zsh_register_fzf_command
#
- name: Download fzf
  unarchive:
    src: "{{ zsh_fzf_url }}"
    dest: /home/{{ zsh_user }}/local/bin
    remote_src: yes
    creates: /home/{{ zsh_user }}/local/bin/fzf
  when: zsh_register_fzf_command.rc == 1

# - name: Install Homebrew packages

# -name: Install linuxbrew
  #export HOMEBREW_BUILD_FROM_SOURCE=1
  #module load gnu/4.9.2

# - name: Install Ruby Gems
